//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CedulaEntities : DbContext
    {
        public CedulaEntities()
            : base("name=CedulaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Colegio> Colegios { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivils { get; set; }
        public virtual DbSet<LugarNacimiento> LugarNacimientoes { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Nacionalidad> Nacionalidads { get; set; }
        public virtual DbSet<Ocupacion> Ocupacions { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<Sexo> Sexoes { get; set; }
        public virtual DbSet<TipoSangre> TipoSangres { get; set; }
        public virtual DbSet<Cedula> Cedulas { get; set; }
    }
}
