//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cedula
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public string DireccionResidencia { get; set; }
        public int IdColegioElectoral { get; set; }
        public int IdNacional { get; set; }
        public int IdLugarNacimiento { get; set; }
        public int IdSexo { get; set; }
        public int IdTipoSangre { get; set; }
        public int IdOcupacion { get; set; }
        public int IdEstadoCivil { get; set; }
        public int IdMunicipio { get; set; }
        public int IdSector { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Colegio Colegio { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        public virtual LugarNacimiento LugarNacimiento { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Nacionalidad Nacionalidad { get; set; }
        public virtual Ocupacion Ocupacion { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual TipoSangre TipoSangre { get; set; }
    }
}
